### ISSUE TITLE
MXBean still using com.jclarity namespace

### ISSUE THREAD

**Issue by RichardWarburton** [AdoptOpenJDK/ForkJoinPoolMonitor#3]
I suspect that you want the MXBean's name to be aligned with your package names, rather than using com.jclarity.

See https://github.com/AdoptOpenJDK/ForkJoinPoolMonitor/blob/cb6ff1de146ba880695a484f7c8bfe100f0ab5f0/src/main/java/java/util/concurrent/ForkJoinPoolMonitor.java#L20

Its also worth noting that you've put the MXBean in the java.util.concurrent package. Is that really the location the interface should go in when all the other management MXBeans are in javax.management?

**Comment by kcpeppe** [comment]
indeed, the ObjectName is an oversight from when the project was moved. However, there is a bigger problem in that if you instantiate a new ForkJoinPool there isn't a good naming convention to follow to tie the new monitor to that pool.
The other MXBeans are in java.lang.management. I guess that is a good argument to put this MXBean there also. I didn't expect for it to survive where it is. In fact I don't expect much, if any of the current implementation to survive.
An even bigger issue is that I've not written requirements for this. It's next on the todo list.

**Comment by kcpeppe** [comment]
These comments have been addressed in the code.
